### ISSUE TITLE
(Re)activation of prev button

### ISSUE THREAD

**Issue by davidhund** [wieringen/tinycarousel#17]
I have a simple carousel with 2 visible items: `$carousel.tinycarousel({ infinite: false, animationTime: 400 });`

Initially the `.prev` button is disabled so I can only go from slide 1 to 2 etc...
- When I proceed to slide 2, the `.prev` is enabled correctly (`.disable` is removed)
However, I can not click on it to go back to slide 1…

So slide 2 is the first slide. I can't go back to 1.
Going to slide 3 I *can* go back to 2, so from there it works normally..

It works correctly on the last slide: when I reach the end `.next` is disabled. Going 1 slide back `.next` is re-enabled again correctly and I can go to the last slide.

My gut-feeling is that the `infinite` funcitonality is a bit buggy. Maybe there's some `index` bug (difference between 0-based or 1-based index?)

**Comment by wieringen** [comment]
Should be fixed in 2.1.8 :)

**Comment by davidhund** [comment]
Awesome, thanks Maarten!

**Comment by hoangnm89** [comment]
thanks
