### ISSUE TITLE
Preventing event propagation

### ISSUE THREAD

**Issue by birge** [wieringen/tinycarousel#19]
I was adding google analytics via a document listener and adding classes to elements I wanted tracked. I noticed I wasn't getting any action from tiny carousel and it is because on the 3 events (crumb click, prev, and next) TC is returning false. I think the original intent was to prevent links from being followed, in which case using preventDefault should do the trick. Thoughts?

**Comment by wieringen** [comment]
Its probably because return false is some what the same as a stopPropagation and preventDefault. And you need the propagation to continue so your analytics picks up the click. So yes for your use case to work return false will probably have to be replaced with preventDefault.

**Comment by birge** [comment]
Right, was the intention of the original implementation to stop propagation? It seems to me the goal would be prevent default as must people are going to add the `.next` class to an A tag and we wouldn't want to follow the href. If your intent wasn't to stop propagation I can submit a PR with just preventDefault.
